version: "3"

services:
  api:
    build:
      context: ./__api
      dockerfile: Dockerfile
    container_name: egresados__api
    restart: unless-stopped
    env_file: .env
    environment:
      MONGO_HOSTNAME: db
    ports:
      - 5000:5000
    volumes:
      - ~/logs:/__api/logs
      - ./__api:/__api
      - node_modules:/__api/node_modules
    networks:
      - app-network
    command: ./wait-for.sh db:27017 -- yarn dev

  db:
    image: mongo:4.2.6-bionic
    container_name: db
    restart: unless-stopped
    env_file: .env
    environment:
      MONGO_INITDB_DATABASE: $MONGO_DB
      MONGO_INITDB_ROOT_USERNAME: $MONGO_USERNAME
      MONGO_INITDB_ROOT_PASSWORD: $MONGO_PASSWORD
    volumes:
      - dbdata:/data/db
    networks:
      - app-network

volumes:
  dbdata:
  node_modules:
networks:
  app-network:
    driver: bridge
