version: "3"

services:
  reverseproxy:
    image: traefik:v2.2.1
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik/traefik.yml:/traefik.yml # Traefik configuration file
      - ./traefik/acme.json:/acme.json # Tell Traefik to save SSL certs here
    networks:
      - frontend

  api:
    build:
      context: ./__api
      dockerfile: Dockerfile.dev
    restart: unless-stopped
    env_file: .env
    expose:
      - $API_PORT
    volumes:
      - ./keys:/keys
      - ./__api:/__api
      - node_modules_api:/__api/node_modules
    networks:
      - backend
      - frontend
    command: ./wait-for.sh db:27017 -- yarn dev

  nuxt:
    build:
      context: ./__client
      dockerfile: Dockerfile.dev
    restart: unless-stopped
    env_file: .env
    links:
      - "api:$API_HOST"
    expose:
      - $NUXT_PORT
    volumes:
      - ./__client:/__client
      - node_modules_client:/__client/node_modules
    labels:
      traefik.enable: true
      traefik.port: $NUXT_PORT
      traefik.http.routers.nuxt.rule: Host(`$NUXT_HOST`)
    networks:
      - frontend

  db:
    image: mongo:4.2.6-bionic
    container_name: db
    restart: unless-stopped
    env_file: .env
    environment:
      MONGO_INITDB_DATABASE: $MONGO_DB
      MONGO_INITDB_ROOT_USERNAME: $MONGO_USERNAME
      MONGO_INITDB_ROOT_PASSWORD: $MONGO_PASSWORD
    volumes:
      - dbdata:/data/db
    networks:
      - backend

volumes:
  dbdata:
  node_modules_api:
  node_modules_client:
networks:
  backend:
    driver: bridge
  frontend:
    driver: bridge
