entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false

# certificatesResolvers:
#   appresolver:
#     acme:
#       email: amaury.tobiasqr@gmail.com
#       storage: /acme.json
#       httpChallenge:
#         entryPoint: web
