<template>
  <div
    v-click-outside="closeMenu"
    class="fixed py-4 w-full bg-dark-highlight z-50"
    style="bottom: 0;"
  >
    <div class="flex items-center justify-around">
      <navbar-menu-button :is-opened="isMenuOpen" @click="isMenuOpen = true" />

      <nuxt-link to="/" class="font-medium text-lg text-dark">DEMO</nuxt-link>
      <nuxt-link
        to="/"
        class="bg-light-highlight rounded-full h-10 w-10 flex-shrink-0 overflow-hidden flex items-center justify-center"
      >
        <span class="text-purple-400 text-xl font-medium">AT</span>
      </nuxt-link>
    </div>
    <transition name="slide-top">
      <div
        v-if="isMenuOpen"
        class="w-full bg-dark-highlight text-white fixed p-4 pb-16 rounded-t-lg"
        style="bottom: 0;"
      >
        <ul class="text-lg flex flex-col items-start">
          <li class="self-end mb-2">
            <navbar-menu-button
              :is-opened="isMenuOpen"
              @click="isMenuOpen = false"
            />
          </li>

          <li
            class="bg-light-highlight rounded-full pr-3 py-1 mb-2 flex items-center"
            @click="isMenuOpen = false"
          >
            <span
              class="bg-light-highlight rounded-full h-10 w-10 flex items-center justify-center"
            >
              <home-icon class="text-white" />
            </span>
            <nuxt-link to="/">Inicio</nuxt-link>
          </li>

          <li
            class="bg-light-highlight rounded-full pr-3 py-1 mb-2 flex items-center"
            @click="isMenuOpen = false"
          >
            <span
              class="bg-light-highlight rounded-full h-10 w-10 flex items-center justify-center"
            >
              <calendar-icon class="text-white" />
            </span>
            <nuxt-link to="/noticias">Noticias</nuxt-link>
          </li>

          <li
            class="bg-light-highlight rounded-full pr-3 py-1 mb-2 flex items-center"
            @click="isMenuOpen = false"
          >
            <span
              class="bg-light-highlight rounded-full h-10 w-10 flex items-center justify-center"
            >
              <user-icon class="text-white" />
            </span>
            <nuxt-link to="/">Perfil</nuxt-link>
          </li>

          <li
            class="bg-light-highlight rounded-full pr-3 py-1 mb-2 flex items-center"
            @click="isMenuOpen = false"
          >
            <span
              class="bg-light-highlight rounded-full h-10 w-10 flex items-center justify-center"
            >
              <settings-icon class="text-white" />
            </span>
            <nuxt-link to="/">Ajustes</nuxt-link>
          </li>
        </ul>
      </div>
    </transition>
  </div>
</template>

<script lang="ts">
import { createComponent, ref } from '@vue/composition-api'
import {
  HomeIcon,
  UserIcon,
  SettingsIcon,
  CalendarIcon
} from 'vue-feather-icons'
import NavbarMenuButton from '~/components/NavbarMenuButton'

export default createComponent({
  components: {
    NavbarMenuButton,
    HomeIcon,
    UserIcon,
    SettingsIcon,
    CalendarIcon
  },
  setup() {
    const isMenuOpen = ref(false)

    const closeMenu = () => (isMenuOpen.value = false)

    return { isMenuOpen, closeMenu }
  }
})
</script>

<style lang="postcss" scoped>
/* ----------------------------------------------
 * Generated by Animista on 2020-2-6 11:41:49
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info.
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation slide-top
 * ----------------------------------------
 */
@keyframes slide-top {
  0% {
    transform: translateY(100%);
  }
  100% {
    transform: translateY(0%);
  }
}
.slide-top-enter-active {
  animation: slide-top 0.3s cubic-bezier(0.25, 0.46, 0.45, 0.94) both;
}
.slide-top-leave-active {
  animation: slide-top 0.3s cubic-bezier(0.25, 0.46, 0.45, 0.94) both reverse;
}
</style>
