<template>
  <div
    v-click-outside="closeMenu"
    class="fixed py-2 w-10/12 bg-white dark:bg-gray-900 z-40 bottom-0 mb-2"
  >
    <div class="flex items-center justify-around">
      <navbar-menu-button :is-opened="isMenuOpen" @click="isMenuOpen = true" />

      <nuxt-link to="/" class="font-medium text-lg">LMAD</nuxt-link>
      <nuxt-link
        to="/"
        class="h-10 w-10 flex-shrink-0 flex items-center justify-center"
      >
        <span class="text-green-400 text-xl">
          <login-variant />
        </span>
      </nuxt-link>
    </div>
    <transition name="slide-top">
      <div
        v-if="isMenuOpen"
        class="absolute w-full bg-white dark:bg-gray-900 py-4 px-6 pb-12 rounded-t-lg bottom-0"
      >
        <ul class="text-lg flex flex-col items-stretch">
          <ul class="self-end flex">
            <li @click="closeMenu()">
              <nuxt-link to="/ajustes" class="p-2 flex items-center">
                <cog-outline />
                <settings-icon />
              </nuxt-link>
            </li>

            <li class="self-end mb-2">
              <navbar-menu-button
                :is-opened="isMenuOpen"
                @click="closeMenu()"
              />
            </li>
          </ul>

          <li class="mb-4" @click="closeMenu()">
            <nuxt-link to="/" class="flex col-gap-1">
              <home-variant-outline />
              Inicio
            </nuxt-link>
          </li>

          <li class="mb-4" @click="closeMenu()">
            <nuxt-link to="/noticias" class="flex col-gap-1">
              <calendar-blank-outline />
              Noticias
            </nuxt-link>
          </li>

          <li class="mb-4" @click="closeMenu()">
            <nuxt-link to="/perfil" class="flex col-gap-1">
              <account-outline />
              Perfil
            </nuxt-link>
          </li>
        </ul>
      </div>
    </transition>
  </div>
</template>

<script lang="ts">
import { defineComponent, ref } from 'nuxt-composition-api'
import CalendarBlankOutline from 'mdi-vue/CalendarBlankOutline.vue'
import HomeVariantOutline from 'mdi-vue/HomeVariantOutline.vue'
import AccountOutline from 'mdi-vue/AccountOutline.vue'
import CogOutline from 'mdi-vue/CogOutline.vue'
import LoginVariant from 'mdi-vue/LoginVariant.vue'
import LogoutVariant from 'mdi-vue/LogoutVariant.vue'

import NavbarMenuButton from '@/components/navigation/NavbarMenuButton'

export default defineComponent({
  components: {
    NavbarMenuButton,
    CalendarBlankOutline,
    HomeVariantOutline,
    AccountOutline,
    CogOutline,
    LoginVariant,
    LogoutVariant,
  },
  setup() {
    const isMenuOpen = ref(false)
    const closeMenu = () => (isMenuOpen.value = false)
    return { isMenuOpen, closeMenu }
  },
})
</script>

<style lang="postcss" scoped>
/* ----------------------------------------------
 * Generated by Animista on 2020-2-6 11:41:49
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info.
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation slide-top
 * ----------------------------------------
 */
@keyframes slide-top {
  0% {
    transform: translateY(100%);
  }
  100% {
    transform: translateY(0%);
  }
}
.slide-top-enter-active {
  animation: slide-top 0.3s cubic-bezier(0.25, 0.46, 0.45, 0.94) both;
}
.slide-top-leave-active {
  animation: slide-top 0.3s cubic-bezier(0.25, 0.46, 0.45, 0.94) both reverse;
}
</style>
